### ISSUE TITLE
TCO22 Stage- leaderboard is navigating to TCO page but opening Overview and not the leaderboard

### ISSUE THREAD

**Issue by swap12875** [topcoder-archive/beta-testing-dashboard#101]
Click on the leaderboard on the TCO22 stage

### actual 

observe the new page i.e TCO 22 is opening the Overview and not the leaderboard tab.

### expected 

the leaderboard should open when click on the leaderboard link

### video
https://user-images.githubusercontent.com/67191980/133472837-63210713-0150-44e7-81d2-863fa44c2844.mp4

**Comment by kkartunov** [comment]
It takes some time for page to load and switch to correct tab.
