### ISSUE TITLE
View All Challenges Link - Issue

### ISSUE THREAD

**Issue by iaminfinite** [topcoder-archive/beta-testing-dashboard#106]
<img width="696" alt="Screen Shot 2021-09-15 at 23 30 04" src="https://user-images.githubusercontent.com/50485425/133472841-474b4198-4d59-435a-b787-d075543ca857.png">
The "View All Challenges" link doesn't work. It leads to an empty page. I think we should fix the URL.

<img width="1679" alt="Screen Shot 2021-09-15 at 23 29 47" src="https://user-images.githubusercontent.com/50485425/133472788-e9ae67f0-fbe1-4a05-b487-39c929a33c57.png">

**Comment by kkartunov** [comment]
Somtimes it takes time for Earn app to load. Closing this as it is not relared to dashboard.
If it still does not work for you @iaminfinite please open issue in related repo: https://github.com/topcoder-platform/micro-frontends-earn-app
