### ISSUE TITLE
Scrollbar is comming in gigs tab

### ISSUE THREAD

**Issue by coderhacker** [topcoder-archive/beta-testing-dashboard#128]
Actual: 

The scrollbar is coming in the gigs tab. please see attached screenshot 

![image](https://user-images.githubusercontent.com/62358241/133473588-6e41301d-b237-40c8-9e38-f439a88bd69e.png)

Expected: Scrollbar should be in a proper design to more user experience.

**Comment by kkartunov** [comment]
@coderhacker what zoom have you applied on the page?

**Comment by coderhacker** [comment]
Please see the attached video for issue @kkartuno

https://user-images.githubusercontent.com/62358241/133801480-f990b4fd-1899-46a0-8ade-847d65e92355.mp4

v
