### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by tosha5252** [topcoder-archive/beta-testing-dashboard#174]
Link to support in the far right column not working.
<img width="316" alt="Screen Shot 2021-09-15 at 11 41 44 AM" src="https://user-images.githubusercontent.com/6400904/133474652-8e8667d3-7028-4e1c-a620-0226332dc862.png">

Need help? Send an email to support@topcoder.com

**Comment by kkartunov** [comment]
@tosha5252 it is a mailtop link. Should open your mail client. Does it for you?

**Comment by tosha5252** [comment]
@kkartunov no

**Comment by kkartunov** [comment]
Probably because you have not mail client configured in the system. The link is working fine as expected.
