### ISSUE TITLE
Issue - Leaderboard Dropdown

### ISSUE THREAD

**Issue by AmitKunjir222** [topcoder-archive/beta-testing-dashboard#200]
Issue 1 - We show Duplicate options with one value including Copilot so we should show unique values.

Issue 2 - Styling of dropdown values is not matching the page it looks little bit dull needs improvement.

![image](https://user-images.githubusercontent.com/53404527/133475422-9b4a009f-87e1-4b72-8af6-81f00608c34a.png)

**Comment by kkartunov** [comment]
Duplicate https://github.com/topcoder-platform/beta-testing-dashboard/issues/287
