### ISSUE TITLE
New Feed Cards Don't Fit the Content Properly

### ISSUE THREAD

**Issue by cagdas001** [topcoder-archive/beta-testing-dashboard#214]
All cards should have equal heights & widths even if the content is shorter.

![chrome_2021-09-15_19-46-14](https://user-images.githubusercontent.com/28513447/133475668-c700ab39-8ab5-40ea-ae76-d4df2b013db4.png)

**Comment by kkartunov** [comment]
Cards apply masonry layout as per design.
