### ISSUE TITLE
BUG - Position content on Ipad Pro

### ISSUE THREAD

**Issue by masramadotcom** [topcoder-archive/beta-testing-dashboard#305]
Based on the attached image, the slider image on the iPad Pro should be at the beginning of the content above, but this is not the same as the display on the mobile, it would be better if can fix it so that all the content looks aligned.

<img width="423" alt="Screenshot 2021-09-16 at 00 07 15" src="https://user-images.githubusercontent.com/63098173/133478285-42992090-ccad-4424-8074-ca7f6298535e.png">
<img width="331" alt="Screenshot 2021-09-16 at 00 06 13" src="https://user-images.githubusercontent.com/63098173/133478292-e3f6e45b-d732-444c-9b86-207a156cad46.png">

**Comment by kkartunov** [comment]
slider is fixed.
Compnent reorder for mobile < 768px. iPadPro is 1024px so it is as desktop. We may have design update for this res...
