### ISSUE TITLE
TCO 22 STAGE - the drop down selection is not completely displayed for the long track names

### ISSUE THREAD

**Issue by swap12875** [topcoder-archive/beta-testing-dashboard#311]
for the drop down of the track names in the TCO22, select any of the track with long name like 'Dev copilot' or 'Design copilot' Observe only the first string is getting displayed on the dropdown,

the dropdown size may be adjusted also the line spacing for these long strings in the drop down should be minimize so as to appear as single track 'DESIGN COPILOT" and not like 'design' and 'copilot' separatly

### snap 

![image](https://user-images.githubusercontent.com/67191980/133478737-a11e62b3-df4a-49db-9c39-9d16b65b0083.png)

**Comment by kkartunov** [comment]
Using ... for the long names.
