### ISSUE TITLE
duplicated Api Call 

### ISSUE THREAD

**Issue by nursoltan-s** [topcoder-archive/beta-testing-dashboard#324]
There is so many V4 api calls performed on dashboard page.

It seems it fetches member handles, I don't think it is really necessary and it may cause performance issues. 

<img width="1035" alt="Screen Shot 2021-09-16 at 01 13 54" src="https://user-images.githubusercontent.com/7783676/133479216-b9fe652e-3872-4eb0-8ad5-f642034f21b7.png">

**Comment by kkartunov** [comment]
This is okay @nursoltan-s. Those are looker calls for the TCO leaderboard.
