### ISSUE TITLE
In Review Challenges showing in the competition

### ISSUE THREAD

**Issue by anshul96go** [topcoder-archive/beta-testing-dashboard#369]
I see the in-review challenges being showed up in the competition window even when I haven't registered for the challenge. I think we shouldn't display these challenges in the top. 

For example, the first NASA challenge is getting displayed to me but I haven't even registered for it and it is in review phase so it is not important.

![image](https://user-images.githubusercontent.com/26899264/133481905-16ada274-080b-4693-92e0-64d995697dbd.png)

**Comment by kkartunov** [comment]
Valid bug. Thanks @anshul96go
