### ISSUE TITLE
TCO22 STAGE 1- Option with duplicate values

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-archive/beta-testing-dashboard#43]
**Steps to Reproduce**

1. Go to the https://beta-community-app.topcoder.com/dashboard
2.  Click on the TCO22  leader board options

**Actual Result(s)**
Seems duplicate options are there

**Expected Result(s)**
Should be every option identical 

**Screen shot**
![image](https://user-images.githubusercontent.com/23450398/133471455-3303095a-0f2d-4943-8287-a80d691e46b8.png)

**Comment by kkartunov** [comment]
Those are multiline options.
