### ISSUE TITLE
$ currency missing in GIGS

### ISSUE THREAD

**Issue by coderhacker** [topcoder-archive/beta-testing-dashboard#48]
Actual: $ Currency missing in GIGS tab.

![image](https://user-images.githubusercontent.com/62358241/133471540-c64054f8-3b5b-4ed6-ba00-e6b41f4f496d.png)

Expected: this should be consistent ie $110 to $120 something like this.

**Comment by jmpld40** [comment]
Yes, good call, we need to add the $, agreed!

**Comment by kkartunov** [comment]
@coderhacker actually, it is not a bug in sense of broken functionality.

**Comment by kkartunov** [comment]
@Dara-K fyi, adding this to v1 fixes.
